version: "3.9"
services:
  caddy:
    container_name: bun-caddy
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - $PWD/infrastructure/local/caddy/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/infrastructure/local/caddy/data:/usr/local/share
      - $PWD/infrastructure/local/caddy/sites:/sites
    environment:
      - XDG_DATA_HOME=/usr/local/share
